// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjqUFtIFVeQEEc_G9XwFRw69pcxEz6LUM',
    appId: '1:184794081587:web:df1d4e5babc295ba673646',
    messagingSenderId: '184794081587',
    projectId: 'fir-flutter-c842c',
    authDomain: 'fir-flutter-c842c.firebaseapp.com',
    storageBucket: 'fir-flutter-c842c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACWYQkvqTSLhGpB5yfwPOtbQMMcwNYuy8',
    appId: '1:184794081587:android:5e61cc291d51bcb6673646',
    messagingSenderId: '184794081587',
    projectId: 'fir-flutter-c842c',
    storageBucket: 'fir-flutter-c842c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAzC9CLuTZRRObqgEuwGRDE7ResxMM1do',
    appId: '1:184794081587:ios:890ef6849abab0dc673646',
    messagingSenderId: '184794081587',
    projectId: 'fir-flutter-c842c',
    storageBucket: 'fir-flutter-c842c.appspot.com',
    iosBundleId: 'com.example.appvalorantfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAzC9CLuTZRRObqgEuwGRDE7ResxMM1do',
    appId: '1:184794081587:ios:890ef6849abab0dc673646',
    messagingSenderId: '184794081587',
    projectId: 'fir-flutter-c842c',
    storageBucket: 'fir-flutter-c842c.appspot.com',
    iosBundleId: 'com.example.appvalorantfinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjqUFtIFVeQEEc_G9XwFRw69pcxEz6LUM',
    appId: '1:184794081587:web:d4c2b073bba47652673646',
    messagingSenderId: '184794081587',
    projectId: 'fir-flutter-c842c',
    authDomain: 'fir-flutter-c842c.firebaseapp.com',
    storageBucket: 'fir-flutter-c842c.appspot.com',
  );
}
